name: flutter_slice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/burger.png
  - assets/sosro.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/burger.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  web: true